---
name: 'Lint PHP code'

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, phpcs

      - name: Run PHP CodeSniffer
        run: phpcs -q --standard=tools/PHPCodeSniffer/Standard/ruleset.xml --report=checkstyle | cs2pr