---
name: 'Lint PHP code'

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  lint-php-syntax:
    name: 'Lint syntax'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.0'
          - '8.2'

    steps:
      # Checkout the repository
      - name: Setup repository
        uses: actions/checkout@v4

      # Install PHP and tools necessary
      - name: Setup PHP
        uses: seravo/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: cs2pr, composer

      # Print Composer version
      - run: composer --version

      # Validate composer.json syntax
      - name: Validate composer.json syntax
        run: composer validate --strict

      # Install development dependencies
      - name: Install development dependencies
        run: composer install --no-interaction --no-progress --ignore-platform-reqs

      # Print Parallel Lint version
      - run: vendor/bin/parallel-lint --version

      # Lint PHP code syntax
      - name: Run PHP Parallel Lint
        run: vendor/bin/parallel-lint
          --show-deprecated
          --checkstyle
          --exclude src/vendor
          seravo-plugin.php src | cs2pr

  lint-php-style:
    name: 'Lint style'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Setup repository
        uses: actions/checkout@v4

      # Install PHP and tools necessary
      - name: Setup PHP
        uses: seravo/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, composer

      # Print Composer version
      - run: composer --version

      # Install development dependencies
      - name: Install development dependencies
        run: composer install --no-interaction --no-progress

      # Print PHP_CodeSniffer version
      - run: vendor/bin/phpcs --version

      # Lint PHP code style
      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs -q
          --standard=tools/PHPCodeSniffer/Standard
          --report=checkstyle | cs2pr
